name: Tidy document
on:
  workflow_dispatch: {}
  push:
    branches:
      - gh-pages

jobs:
  tidy:
    name: Tidy up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tidy/html5
        run: sudo apt-get install -y tidy
      - run: tidy -config tidyconfig.txt -o index.html index.html
      - uses: peter-evans/create-pull-request@v5
        with:
          title: "Tidied up document using tidy-html5"
          commit-message: "chore: tidy up index.html"
          branch: html-tidy
